POST http://localhost:3001/api/frontpage
Content-Type: application/json

{
      "user_id": 1,
      "type": "expense",
      "sum": 21,
      "category": "Restaurants",
      "title": "Mcdonalds",
      "date": "2025-01-30"
}