POST http://localhost:3001/api/frontpage
Content-Type: application/json

{
      "type": "expense",
      "sum": 29,
      "category": "Restaurants",
      "title": "dinner",
      "date": "10.1.2025"
}
