POST http://localhost:3001/api/frontpage
Content-Type: application/json

{
      "user_id": 7,
      "type": "expense",
      "sum": 89,
      "category": "Clothes",
      "title": "new shoes",
      "date": "2025-01-29"
}